version: '2'
services:
  bot:
    image: tomcat:7-jre8
    environment:
      IDA_CHAT_BOT_TOKEN: "200885881:AAEb0OmQITvVXqAN0yoUqHMZXYyHG75uHwg"
    ports:
     - "7001:8080"
    volumes:
     - ./bot/target/bot.war:/usr/local/tomcat/webapps/bot.war
     - ./bot/server-docker.xml:/usr/local/tomcat/conf/server.xml
    depends_on:
     - db
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: ida_bot
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: s3cr3t