---
- name: Stop tomcat7 service
  service: name=tomcat7 state=stopped
  become: yes
  become_method: sudo

- name: Copy server.xml
  copy: src=../bot/server-production.xml dest=/etc/tomcat7/server.xml mode=0644
  become: yes
  become_method: sudo

- name: Remove old deployment directory
  file: dest=/var/lib/tomcat7/webapps/bot state=absent
  become: yes
  become_method: sudo

- name: Copy new WAR file
  copy: src=../bot/target/bot.war dest=/var/lib/tomcat7/webapps owner=tomcat7 mode=0644
  become: yes
  become_method: sudo

- name: Start tomcat7 service
  service: name=tomcat7 state=started
  become: yes
  become_method: sudo


