---
 - hosts: production
   tasks:
    - name: Ensure bot directory exist
      file: path=~/bot state=directory

    - name: Copy built jar
      copy: src=../bot/target/bot.jar dest=~/bot/bot.jar

    - name: Copy libs
      copy: src=../bot/target/lib dest=~/bot

    - name: Kill existing instance of the app
      become: yes
      become_method: sudo
      shell: pkill -f bot
      ignore_errors: yes

    - name: Start bot application
      shell: nohup java -jar ~/bot/bot.jar &
      register: start_bot

    - debug: msg="{{ start_bot.stdout }}"

